In [1]:
print("Logistic Regression")

Logistic Regression


In [4]:
# Importing requried libraries
import pandas as pd
import numpy as np
from sklearn import preprocessing
from scipy import stats

In [5]:
# Data Collection 

In [ ]:
#Click here and press Shift+Enter
!wget -O ChurnData.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/ChurnData.csv

In [8]:
df = pd.read_csv("ChurnData.csv")

In [9]:
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [10]:
df.shape

(200, 28)

In [11]:
df.isnull().values.sum()

0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
tenure      200 non-null float64
age         200 non-null float64
address     200 non-null float64
income      200 non-null float64
ed          200 non-null float64
employ      200 non-null float64
equip       200 non-null float64
callcard    200 non-null float64
wireless    200 non-null float64
longmon     200 non-null float64
tollmon     200 non-null float64
equipmon    200 non-null float64
cardmon     200 non-null float64
wiremon     200 non-null float64
longten     200 non-null float64
tollten     200 non-null float64
cardten     200 non-null float64
voice       200 non-null float64
pager       200 non-null float64
internet    200 non-null float64
callwait    200 non-null float64
confer      200 non-null float64
ebill       200 non-null float64
loglong     200 non-null float64
logtoll     200 non-null float64
lninc       200 non-null float64
custcat     200 non-null float64
chur

Lets select some features for the modeling. Also we change the target data type to be integer, as it is a requirement  by the skitlearn algorithm:

In [13]:
df['churn'].value_counts()

0.0    142
1.0     58
Name: churn, dtype: int64

In [14]:
df['churn'].dtype

dtype('float64')

In [15]:
df['churn'] = df['churn'].astype('int')

In [17]:
df['churn'].dtype

dtype('int32')

In [19]:
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [20]:
x = df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']].values

In [21]:
x

array([[11., 33.,  7., ...,  5.,  5.,  0.],
       [33., 33., 12., ...,  2.,  0.,  0.],
       [23., 30.,  9., ...,  1.,  2.,  0.],
       ...,
       [ 6., 32., 10., ...,  1., 10.,  0.],
       [24., 30.,  0., ...,  4.,  5.,  0.],
       [61., 50., 16., ...,  2., 22.,  1.]])

In [22]:
x1 = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])

In [23]:
x1

array([[11., 33.,  7., ...,  5.,  5.,  0.],
       [33., 33., 12., ...,  2.,  0.,  0.],
       [23., 30.,  9., ...,  1.,  2.,  0.],
       ...,
       [ 6., 32., 10., ...,  1., 10.,  0.],
       [24., 30.,  0., ...,  4.,  5.,  0.],
       [61., 50., 16., ...,  2., 22.,  1.]])

In [24]:
y = df['churn']

In [25]:
y

0      1
1      1
2      0
3      0
4      0
      ..
195    0
196    0
197    0
198    1
199    0
Name: churn, Length: 200, dtype: int32

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
s = StandardScaler()

In [30]:
x = s.fit(x).transform(x)

In [31]:
x

array([[-1.13518441, -0.62595491, -0.4588971 , ...,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, ..., -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , ..., -1.42318853,
        -0.92053635, -0.85972695],
       ...,
       [-1.36680743, -0.7026181 , -0.16283445, ..., -1.42318853,
        -0.02518185, -0.85972695],
       [-0.53296457, -0.85594447, -1.14970993, ...,  0.91629947,
        -0.58477841, -0.85972695],
       [ 1.18104577,  0.67731925,  0.42929083, ..., -0.6433592 ,
         1.31784991,  1.16316   ]])

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
xtr, xte, ytr, yte = train_test_split(x,y, test_size = 0.2, random_state= 0)

In [34]:
xtr.shape

(160, 7)

In [35]:
xte.shape

(40, 7)

In [36]:
ytr.shape

(160,)

In [37]:
yte.shape


(40,)

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
lr = LogisticRegression()

In [41]:
lr.fit(xtr,ytr)

F:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [42]:
yaht = lr.predict(xte)

In [43]:
yaht[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [44]:
yte[:10]

18     0
170    0
107    1
98     0
177    0
182    0
5      0
146    0
12     0
152    1
Name: churn, dtype: int32

In [45]:
lr.score(xte,yte)

0.8

In [46]:
L = LogisticRegression(C = 0.01, solver = 'libliner')

In [48]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(xtr,ytr)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

**predict_proba** returns estimates for all classes, ordered by the label of classes. So, the first column is the probability of class 1, P(Y=1|X), and second column is probability of class 0, P(Y=0|X):

In [50]:
yhat_prob = LR.predict_proba(xte)
yhat_prob

array([[0.50402483, 0.49597517],
       [0.50621147, 0.49378853],
       [0.46765299, 0.53234701],
       [0.70586322, 0.29413678],
       [0.60383767, 0.39616233],
       [0.64103976, 0.35896024],
       [0.72681594, 0.27318406],
       [0.49745877, 0.50254123],
       [0.6701803 , 0.3298197 ],
       [0.46223601, 0.53776399],
       [0.56865845, 0.43134155],
       [0.73425275, 0.26574725],
       [0.56507262, 0.43492738],
       [0.75573883, 0.24426117],
       [0.65493928, 0.34506072],
       [0.47547897, 0.52452103],
       [0.50596737, 0.49403263],
       [0.81776537, 0.18223463],
       [0.51697745, 0.48302255],
       [0.5441984 , 0.4558016 ],
       [0.68835582, 0.31164418],
       [0.56906378, 0.43093622],
       [0.70181188, 0.29818812],
       [0.46953454, 0.53046546],
       [0.69401498, 0.30598502],
       [0.41515778, 0.58484222],
       [0.65823962, 0.34176038],
       [0.50146349, 0.49853651],
       [0.43382404, 0.56617596],
       [0.47018019, 0.52981981],
       [0.

In [ ]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

In [53]:
from sklearn.metrics import jaccard_similarity_score as j

In [58]:
j(yte, yhat_prob)

F:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:635: DeprecationWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  'and multiclass classification tasks.', DeprecationWarning)


ValueError: Classification metrics can't handle a mix of binary and continuous-multioutput targets

In [56]:
from sklearn.metrics import log_loss
log_loss(yte, yhat_prob)

0.5562764596237845