In [1]:
print("SVM")

SVM


In [2]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
#Click here and press Shift+Enter
!wget -O cell_samples.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/cell_samples.csv

In [28]:
df = pd.read_csv('cell_samples.csv')

In [29]:
df.head()

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [30]:
df.shape

(699, 11)

In [31]:
df.isnull().values.sum()

0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
ID             699 non-null int64
Clump          699 non-null int64
UnifSize       699 non-null int64
UnifShape      699 non-null int64
MargAdh        699 non-null int64
SingEpiSize    699 non-null int64
BareNuc        699 non-null object
BlandChrom     699 non-null int64
NormNucl       699 non-null int64
Mit            699 non-null int64
Class          699 non-null int64
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [33]:
df.describe(include = 'all')

ID       Clump    UnifSize   UnifShape     MargAdh  \
count   6.990000e+02  699.000000  699.000000  699.000000  699.000000   
unique           NaN         NaN         NaN         NaN         NaN   
top              NaN         NaN         NaN         NaN         NaN   
freq             NaN         NaN         NaN         NaN         NaN   
mean    1.071704e+06    4.417740    3.134478    3.207439    2.806867   
std     6.170957e+05    2.815741    3.051459    2.971913    2.855379   
min     6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%     8.706885e+05    2.000000    1.000000    1.000000    1.000000   
50%     1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%     1.238298e+06    6.000000    5.000000    5.000000    4.000000   
max     1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        SingEpiSize BareNuc  BlandChrom    NormNucl         Mit       Class  
count    699.000000     699  699.000000  699.000000  699.000000  699.000000  
unique          NaN      11         NaN         NaN         NaN         NaN  
top             NaN       1         NaN         NaN         NaN         NaN  
freq            NaN     402         NaN         NaN         NaN         NaN  
mean       3.216023     NaN    3.437768    2.866953    1.589413    2.689557  
std        2.214300     NaN    2.438364    3.053634    1.715078    0.951273  
min        1.000000     NaN    1.000000    1.000000    1.000000    2.000000  
25%        2.000000     NaN    2.000000    1.000000    1.000000    2.000000  
50%        2.000000     NaN    3.000000    1.000000    1.000000    2.000000  
75%        4.000000     NaN    5.000000    4.000000    1.000000    4.000000  
max       10.000000     NaN   10.000000   10.000000   10.000000    4.000000

In [34]:
df.columns

Index(['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit', 'Class'],
      dtype='object')

In [35]:
df['Class'].value_counts()

2    458
4    241
Name: Class, dtype: int64

In [36]:
df['BareNuc'].value_counts()

1     402
10    132
5      30
2      30
3      28
8      21
4      19
?      16
9       9
7       8
6       4
Name: BareNuc, dtype: int64

In [39]:
r  = df['BareNuc'] 

In [64]:
df['BareNuc'] = df['BareNuc'].replace("?", np.nan)

In [65]:
df['BareNuc'].isnull().any()

True

In [66]:
df.isnull().sum()

ID              0
Clump           0
UnifSize        0
UnifShape       0
MargAdh         0
SingEpiSize     0
BareNuc        16
BlandChrom      0
NormNucl        0
Mit             0
Class           0
dtype: int64

In [71]:
df.shape

(699, 11)

In [72]:
df.dropna(inplace= True)

In [73]:
df.isnull().any()

ID             False
Clump          False
UnifSize       False
UnifShape      False
MargAdh        False
SingEpiSize    False
BareNuc        False
BlandChrom     False
NormNucl       False
Mit            False
Class          False
dtype: bool

Now our data is fully clean

In [74]:
df.columns

Index(['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit', 'Class'],
      dtype='object')

In [78]:
x = df[['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit']].values

In [79]:
x.shape

(683, 10)

In [81]:
x[:10]

array([[1000025, 5, 1, 1, 1, 2, '1', 3, 1, 1],
       [1002945, 5, 4, 4, 5, 7, '10', 3, 2, 1],
       [1015425, 3, 1, 1, 1, 2, '2', 3, 1, 1],
       [1016277, 6, 8, 8, 1, 3, '4', 3, 7, 1],
       [1017023, 4, 1, 1, 3, 2, '1', 3, 1, 1],
       [1017122, 8, 10, 10, 8, 7, '10', 9, 7, 1],
       [1018099, 1, 1, 1, 1, 2, '10', 3, 1, 1],
       [1018561, 2, 1, 2, 1, 2, '1', 3, 1, 1],
       [1033078, 2, 1, 1, 1, 2, '1', 1, 1, 5],
       [1033078, 4, 2, 1, 1, 2, '1', 2, 1, 1]], dtype=object)

In [87]:
df["Class"].dtype

dtype('int64')

In [88]:
df['Class'] = df['Class'].astype('int')

In [89]:
df['Class'].dtype

dtype('int32')

In [90]:
y = df['Class']

In [91]:
y

0      2
1      2
2      2
3      2
4      2
      ..
694    2
695    2
696    4
697    4
698    4
Name: Class, Length: 683, dtype: int32

In [92]:
y.shape

(683,)

In [93]:
from sklearn.model_selection import train_test_split

In [94]:
xtr, xte , ytr,yte = train_test_split(x,y,test_size = 0.2, random_state= 0)

In [95]:
xtr.shape

(546, 10)

In [96]:
xte.shape

(137, 10)

In [97]:
ytr.shape

(546,)

In [98]:
yte.shape

(137,)

The SVM algorithm offers a choice of kernel functions for performing its processing. Basically, mapping data into a higher dimensional space is called kernelling. The mathematical function used for the transformation is known as the kernel function, and can be of different types, such as:

    1.Linear
    2.Polynomial
    3.Radial basis function (RBF)
    4.Sigmoid
Each of these functions has its characteristics, its pros and cons, and its equation, but as there's no easy way of knowing which function performs best with any given dataset, we usually choose different functions in turn and compare the results. Let's just use the default, RBF (Radial Basis Function).

In [100]:
from sklearn import svm


In [101]:
model = svm.SVC(kernel = 'rbf')


In [102]:
model.fit(xtr,ytr)

F:\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [103]:
yhat = model.predict(xte)

In [104]:
yhat

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2])

In [106]:
np.asarray(yte)

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 2,
       4, 2, 4, 2, 4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2])

In [107]:
model.score(xte,yte)

0.635036496350365

In [108]:
# Evalutating the model

In [110]:
from sklearn.metrics import f1_score
f1_score(yte, yhat, average='weighted') 

F:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


0.49328727841501563

In [111]:
model2 = svm.SVC(kernel = 'linear')

In [113]:
model2.fit(xtr, ytr)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [114]:
yaht2 = model2.predict(xte)

In [116]:
yaht2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 4, 2, 2])

In [117]:
model2.score(xte,yte)

0.635036496350365

In [ ]:
from sklearn.metrics import f1_score
f1_score(yte, yhat, average='weighted') 